# Generated by Django 5.2.4 on 2025-07-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_ideastar'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtool',
            name='kind',
            field=models.CharField(default='기타', max_length=50),
        ),
    ]
