# Generated by Django 5.2.4 on 2025-07-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostargram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
